### ISSUE TITLE
Is this sketch only compatible with the SparkFun MIDI-shield? 

### ISSUE THREAD

**Issue by m-r-m-s** [sparkfun/MIDI_Shield#16]
I am _not_ using the sparkfun MIDI shield but I have built a MIDI I/O circuit according to MIDI specs.

The MIDI I/O circuit works with no issues when receiving input from a sequencer and the output goes to a software synthesizer sound source. Here is a [link](https://forum.arduino.cc/index.php?topic=699623.msg4702301#msg4702301) to the I/O circuit I have built.

I have tested this circuit using the Arduino MIDI library (fortyseven effects) basic I/O and callback examples. No issues whatsoever.

The issue I am having with the MIDI-sniffer.ino sketch is that while the serial monitor seems to be reading all the MIDI data, the output seems to be getting "stuck". Notes sent from the sequencer will get stuck "on", and after I stop the sequencer, I hear a distinct echo/ feedback noise coming from the receiving sound source. 

As a result, I have to reset the MIDI output (send note off / panic message) in my DAW to stop the noise from continuing and "unstick" things. Is this some kind of loopback?

Why do the basic I/O and callback examples provided in the Arduino MIDI library work but this sketch has issues? How can I work to resolve this issue? Any guidance or pointers is greatly appreciated.

**Comment by Jacquot-SFE** [comment]
So the dirty little secret of NewSoftSerial - it's half-duplex.  Sending and receiving at the same time can interfere with one another.  It'll get worse as the port utilization rises - tapping one key on a MIDI controller might be OK, while heavy multi-channel sequencer (with clocks, controllers, etc) data might not.

There are a couple things to try.

To have a reliable MIDI-thru for the sniffer, you could feed the TTL signal recovered from the input straight to the output driver - that would be akin to the out/thru solder jumper (SJ3) on the shield.

Alternatively, use a chip with multiple hardware UARTs, like an Arduino Mega or Teensy.

**Comment by m-r-m-s** [comment]
@Jacquot-SFE  Thank you! I figured it was something related to the sequencer's heavier input and you have certainly confirmed it. I am currently working with an UNO but will consider the Mega or Teensy for the future. 

In the meantime, can you say more about "feeding the TTL signal recovered from the input straight to the output driver"?

Currently, I have a sequencer connected to my MIDI IN circuit which is connected to pin 8 (Rx) on the UNO and the MIDI OUT circuit is connected at pin 9 (Tx). Apologies in advance for the lack of knowledge, but how would I achieve what you suggested in this in the circuit? 

For reference, these are the schematics of my [input](https://www.limulo.net/website/assets/images/midi-interface/MIDI_IN_bb_new.png) and [output](https://www.limulo.net/website/assets/images/midi-interface/MIDI_OUT_bb_new.png) circuit. Thank you for all the assistance so far.

**Comment by Jacquot-SFE** [comment]
To make the out into a thru, unplug the purple with from Arduino pin 10.  Plug it into pin 6 of the optocoupler, where the green wire to Ard 11 is.

It's probably not the most robust solution - a typical MIDI thru uses a logic gate of some sort to buffer & drive the thru.  The shield uses a 74ahc1g125, the old MMA circuit uses series pairs of inverters (invert, then invert again).

**Comment by m-r-m-s** [comment]
@Jacquot-SFE thank you so so much. Just gave the thru circuit a try and it worked great! I really appreciate your guidance here. I will look into building a more robust MIDI thru circuit with the buffer you referenced.
