### ISSUE TITLE
Verify/compile of MIDI-sniffer fails

### ISSUE THREAD

**Issue by kciszewski** [sparkfun/MIDI_Shield#17]
When compiling on Aurdiuno IDE the error message "MIDI-sniffer:41:10: fatal error: MsTimer2.h: No such file or directory
 #include <MsTimer2.h>"

I'm using Arduino 1.8.19

Where do I find MsTimer2.h?

**Comment by kciszewski** [comment]
I found it thanks!  I'm somewhat new to Arduino

**Comment by edspark** [comment]
MsTImer2 is an [Arduino Library](https://www.arduino.cc/reference/en/libraries/mstimer2/) that you can find using the Library Manger. I don't have 1.8 on my computer but it's an old library that still exists even in Arduino 2.2.

**Comment by edspark** [comment]
Ah you beat me to it, cheers!
