### ISSUE TITLE
net labels need to all be flag style in sch

### ISSUE THREAD

**Issue by ghost** [sparkfun/MIDI_Shield#6]
Change net labels on A0, A1, D2, D3, D4, D6, and D7 to flag style. Use the "PORT-RX" net labels of R2 as the model to emulate.

**Comment by Jacquot-SFE** [comment]
My understanding was that we use flags to indicate that a net is broken
across areas of the sheet, but net labels when we want to indicate net
name, but it's unbroken.

For instance, the Thing intermixes both styles (Note the VUSB and VBAT in
towards to top left):
https://cdn.sparkfun.com/datasheets/Wireless/WiFi/SparkFun_ESP8266_Thing.pdf

Do I misunderstand this?

**Comment by ghost** [comment]
That would make sense as the set rule. I've just seen the flag style used in all cases where it was easy enough to implement because it "looks better" but I prefer your reasoning.
