### ISSUE TITLE
version number correct?

### ISSUE THREAD

**Issue by ghost** [sparkfun/MIDI_Shield#8]
I think standard protocol dictates that the version number should still be v15 even though we proto'd a v15 already, only because the live version of the product is v14. The version increment should stay v15 through however many rounds of proto we do in this case. Toni, can you confirm?

**Comment by Jacquot-SFE** [comment]
You're right.  

(As Per an old discussion with Abe) They never made it to production, so it won't introduce inventory problems if the number doesn't roll.

Back to 1.5.
